
steps:
  # Build the Docker image with timeout extension
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/fastgrapher-repo/fastgrapher-backend', '.']
    timeout: '1200s'
    
  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/fastgrapher-repo/fastgrapher-backend']
    timeout: '600s'
    
  # Deploy to Cloud Run with optimized settings
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
      - 'run'
      - 'deploy'
      - 'backend-fastgrapher-service'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/fastgrapher-repo/fastgrapher-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'MONGO_URI=MONGO_URI:latest'
      - '--set-secrets'
      - 'JWT_SECRET=JWT_SECRET:latest'
      - '--set-secrets'
      - 'MAIL_HOST=MAIL_HOST:latest'
      - '--set-secrets'
      - 'MAIL_PORT=MAIL_PORT:latest'
      - '--set-secrets'
      - 'MAIL_SECURE=MAIL_SECURE:latest'
      - '--set-secrets'
      - 'MAIL_USER=MAIL_USER:latest'
      - '--set-secrets'
      - 'MAIL_PASS=MAIL_PASS:latest'
      - '--set-secrets'
      - 'MAIL_FROM=MAIL_FROM:latest'
      - '--timeout'
      - '900s'
      - '--cpu'
      - '2'
      - '--memory'
      - '1Gi'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--cpu-throttling'
      - '--startup-cpu-boost'

options:
  machineType: 'E2_HIGHCPU_8'
  
# Store the image in Artifact Registry
images: ['us-central1-docker.pkg.dev/$PROJECT_ID/fastgrapher-repo/fastgrapher-backend']
