apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nestjs-app
  namespace: default
  labels:
    app: nestjs-app
spec:
  template:
    spec:
      containers:
        # - image: gcr.io/YOUR_PROJECT_ID/nestjs-app:latest
        - image: gcr.io/fastgrapher-460722/nestjs-app:latest
          name: nestjs-app-container
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: 'production'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_URL
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
  traffic:
    - latestRevision: true
      percent: 100
