
name: Build and Deploy to GKE

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  ZONE: ${{ secrets.GKE_ZONE }}
  REGISTRY: europe-west2-docker.pkg.dev
  REPOSITORY: nestjs-repo
  IMAGE: nestjs-app

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Setup gcloud CLI
    - name: Setup GCP Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v2

    # Configure Docker to use gcloud as credential helper for Artifact Registry
    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.REGISTRY }}

    # Build and push Docker image
    - name: Build and Push
      run: |-
        cd server
        docker build \
          -t "${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}" \
          -t "${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest" .
        docker push "${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}"
        docker push "${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest"

    # Deploy to GKE
    - name: Deploy
      run: |-
        gcloud container clusters get-credentials "${{ env.CLUSTER_NAME }}" \
          --zone "${{ env.ZONE }}" \
          --project "${{ env.PROJECT_ID }}"
        
        # Update the image in the deployment
        kubectl set image deployment/nestjs-app \
          nestjs-app="${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}" \
          --record
        
        # Apply any changes to k8s configs
        kubectl apply -f server/k8s/
        
        # Wait for rollout to complete
        kubectl rollout status deployment/nestjs-app
