name: Deploy to Google Cloud Run

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: backend-fastgrapher-service
  REGION: us-central1
  REPOSITORY: fastgrapher-repo
  IMAGE_NAME: fastgrapher-backend

permissions:
  contents: 'read'
  id-token: 'write'  # This is required for Workload Identity Federation

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Authenticate using Workload Identity
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          create_credentials_file: true
          # Remove any audience parameter to use GitHub's default

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Deploy
        run: |-
          gcloud builds submit \
            --tag ${{ env.REGION }}-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA \
            --project=$PROJECT_ID \
            --timeout=1200s

          gcloud run deploy $SERVICE_NAME \
            --image ${{ env.REGION }}-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars NODE_ENV=production \
            --set-secrets=MONGO_URI=MONGO_URI:latest \
            --set-secrets=JWT_SECRET=JWT_SECRET:latest \
            --timeout=900s \
            --cpu=2 \
            --memory=1Gi