name: Build and Deploy to GKE

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  ZONE: ${{ secrets.GKE_ZONE }}
  IMAGE: ${{ secrets.IMAGE_REGISTRY }}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - name: Setup GCP Auth
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Configure Docker to use gcloud as credential helper
    - name: Configure Docker
      run: gcloud auth configure-docker europe-west2-docker.pkg.dev

    # Build and push Docker image
    - name: Build
      run: |-
        docker build \
          -t "$IMAGE:$GITHUB_SHA" \
          -t "$IMAGE:latest" .
        docker push "$IMAGE:$GITHUB_SHA"
        docker push "$IMAGE:latest"

    # Deploy to GKE
    - name: Deploy
      run: |-
        gcloud container clusters get-credentials "$CLUSTER_NAME" \
          --zone "$ZONE" \
          --project "$PROJECT_ID"
        kubectl apply -f k8s/
        kubectl rollout restart deployment nestjs-app