
name: Deploy to Google Cloud Run

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'

env:
  PROJECT_ID: backend-fastgrapher
  SERVICE_NAME: backend-fastgrapher-service
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/741083673218/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'github-actions-sa@backend-fastgrapher.iam.gserviceaccount.com'
          
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Build and Deploy
        run: |-
          gcloud builds submit \
            --tag us-central1-docker.pkg.dev/$PROJECT_ID/fastgrapher-repo/fastgrapher-backend:$GITHUB_SHA \
            --project=$PROJECT_ID

          gcloud run deploy $SERVICE_NAME \
            --image us-central1-docker.pkg.dev/$PROJECT_ID/fastgrapher-repo/fastgrapher-backend:$GITHUB_SHA \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars NODE_ENV=production \
            --set-secrets=MONGO_URI=MONGO_URI:latest \
            --set-secrets=JWT_SECRET=JWT_SECRET:latest \
            --set-secrets=MAIL_HOST=MAIL_HOST:latest \
            --set-secrets=MAIL_PORT=MAIL_PORT:latest \
            --set-secrets=MAIL_SECURE=MAIL_SECURE:latest \
            --set-secrets=MAIL_USER=MAIL_USER:latest \
            --set-secrets=MAIL_PASS=MAIL_PASS:latest \
            --set-secrets=MAIL_FROM=MAIL_FROM:latest \
            --timeout=300s \
            --cpu=1 \
            --memory=512Mi \
            --min-instances=1 \
            --max-instances=3 \
            --concurrency=80
