name: Deploy FastGrapher Backend to Hetzner

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Hetzner Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 37.27.2.53
        username: root
        key: ${{ secrets.HETZNER_SSH_KEY }}
        timeout: 300s
        script: |
          echo "=== Starting FastGrapher Backend Deployment ==="
          
          # Navigate to application directory
          cd /opt/fastgrapher || { echo "Application directory not found"; exit 1; }
          
          # Configure Git safe directory
          echo "Configuring Git safe directory..."
          git config --global --add safe.directory /opt/fastgrapher
          
          # Pull latest changes
          echo "Pulling latest changes from GitHub..."
          git pull origin main || { echo "Git pull failed"; exit 1; }
          
          # Stop and remove existing containers
          echo "Stopping existing containers..."
          docker-compose -f docker-compose.hetzner.yml down || true
          
          # Remove old images to save space
          echo "Cleaning up old Docker images..."
          docker image prune -f || true
          
          # Build and start new containers
          echo "Building and starting new containers..."
          docker-compose -f docker-compose.hetzner.yml up -d --build
          
          # Wait for container to be healthy
          echo "Waiting for container to be healthy..."
          sleep 30
          
          # Check if container is running
          if docker-compose -f docker-compose.hetzner.yml ps | grep -q "Up"; then
            echo "✅ Container is running"
          else
            echo "❌ Container failed to start"
            docker-compose -f docker-compose.hetzner.yml logs
            exit 1
          fi
          
          # Test health endpoint
          echo "Testing health endpoint..."
          if curl -f http://localhost:8080/api/health; then
            echo "✅ Health check passed"
          else
            echo "❌ Health check failed"
            docker-compose -f docker-compose.hetzner.yml logs
            exit 1
          fi
          
          echo "=== Deployment completed successfully ==="